version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:9000"
        volumes:
            - .:/var/www
        depends_on:
            - db

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: taskmanagement
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
